### ISSUE TITLE
Cannot turn on persistance.

### ISSUE THREAD

**Issue by saqibarshad** [tosinonikute/Carteasy#6]
cs.persistData(getApplicationContext, true);
does not work. Even after adding this line of code, when I restart my application everything starts all over again. Please  tell me how to fix this. Or how to use it properly.

**Comment by tosinonikute** [comment]
This should work as expected

```
val cs = Carteasy()
cs.persistData(applicationContext, true)
... then add your objects

cs.add(productId, "product name", "XXXX")
cs.commit(applicationContext)
```
Can I see your code?
